import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import { Suspense } from "react"
import EnvironmentBadge from "@/components/base/EnvironmentBadge"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

/**
 * @todo NowLoading
 */ 
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const environment = String(process.env.ENVIRONMENT_NAME)

  return (
    <html lang="ja">
      <body className={inter.className}>
        {environment !== 'LIVE' ? <EnvironmentBadge environment={environment} /> : <></>}
        <Suspense fallback={<div>Now loading...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  )
}
export default RootLayout
